-- ============================================================================
-- Kraefegg M.O. - Migração das demais entidades do HQ para o schema PUBLIC
-- (agentes, projetos, demandas) acessíveis via REST/Supabase.
--
-- O schema original (db/schema.sql) define o núcleo no schema "kraefegg".
-- Porém a API REST do Supabase expõe somente o schema "public" por padrão.
-- A tabela public.relatorios já está exposta e funcionando. Esta migração
-- replica o MESMO padrão (GRANT + ROW LEVEL SECURITY + POLICY) para as
-- entidades que o HQ consome: agentes, projetos e demandas.
--
-- COMO APLICAR:  Supabase Dashboard -> SQL Editor -> colar e rodar.
-- ============================================================================

BEGIN;

-- ============================= AGENTES =====================================
CREATE TABLE IF NOT EXISTS public.agentes (
    id            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo        text UNIQUE NOT NULL,
    nome          text NOT NULL,
    cargo         text,
    area          text,
    funcao        text,
    especialidade text,
    modelo_ia     text NOT NULL DEFAULT 'omniroute/auto/best-reasoning',
    permissao     jsonb NOT NULL DEFAULT '{}'::jsonb,
    ativo         boolean NOT NULL DEFAULT true,
    criado_em     timestamptz NOT NULL DEFAULT now()
);

-- ============================= PROJETOS ====================================
CREATE TABLE IF NOT EXISTS public.projetos (
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      text UNIQUE NOT NULL,
    nome        text NOT NULL,
    descricao   text,
    responsavel text,
    status      text NOT NULL DEFAULT 'backlog'
                CHECK (status IN ('backlog','analise','execucao','revisao','concluido','cancelado')),
    prioridade  text NOT NULL DEFAULT 'media'
                CHECK (prioridade IN ('baixa','media','alta','critica')),
    progresso   numeric(5,1) NOT NULL DEFAULT 0 CHECK (progresso BETWEEN 0 AND 100),
    data_inicio date,
    data_fim    date,
    criado_em   timestamptz NOT NULL DEFAULT now(),
    atualizado_em timestamptz NOT NULL DEFAULT now()
);

-- ============================= DEMANDAS (tarefas) ==========================
CREATE TABLE IF NOT EXISTS public.demandas (
    id            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo        text UNIQUE NOT NULL,
    titulo        text NOT NULL,
    descricao     text,
    projeto_id    int REFERENCES public.projetos(id) ON DELETE SET NULL,
    area          text,
    responsavel   text,
    fase          text NOT NULL DEFAULT 'backlog'
                  CHECK (fase IN ('backlog','analise','execucao','revisao','concluida')),
    prioridade    text NOT NULL DEFAULT 'media'
                  CHECK (prioridade IN ('baixa','media','alta','critica')),
    progresso     int NOT NULL DEFAULT 0 CHECK (progresso BETWEEN 0 AND 100),
    prazo         date,
    criado_em     timestamptz NOT NULL DEFAULT now(),
    atualizado_em timestamptz NOT NULL DEFAULT now()
);

-- ============================= ACESSO API ===================================
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.agentes  TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.projetos TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demandas TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.agentes_id_seq  TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.projetos_id_seq TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.demandas_id_seq TO anon, authenticated;

-- ============================= ROW LEVEL SECURITY ===========================
ALTER TABLE public.agentes  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projetos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.demandas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS agentes_anon_all  ON public.agentes;
DROP POLICY IF EXISTS projetos_anon_all ON public.projetos;
DROP POLICY IF EXISTS demandas_anon_all ON public.demandas;
DROP POLICY IF EXISTS agentes_auth_all  ON public.agentes;
DROP POLICY IF EXISTS projetos_auth_all ON public.projetos;
DROP POLICY IF EXISTS demandas_auth_all ON public.demandas;

CREATE POLICY agentes_anon_all  ON public.agentes  FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY projetos_anon_all ON public.projetos FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY demandas_anon_all ON public.demandas FOR ALL TO anon USING (true) WITH CHECK (true);

CREATE POLICY agentes_auth_all  ON public.agentes  FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY projetos_auth_all ON public.projetos FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY demandas_auth_all ON public.demandas FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ============================= ATUALIZADO_EM ================================
CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.atualizado_em := now();
    RETURN NEW;
END; $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_projetos_updated ON public.projetos;
DROP TRIGGER IF EXISTS trg_demandas_updated ON public.demandas;
CREATE TRIGGER trg_projetos_updated BEFORE UPDATE ON public.projetos FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_demandas_updated BEFORE UPDATE ON public.demandas FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================= SEED INICIAL =================================
-- Agentes-chave (apenas se a tabela estiver vazia)
DO $$
BEGIN
    IF (SELECT count(*) FROM public.agentes) = 0 THEN
        INSERT INTO public.agentes (codigo, nome, cargo, area, funcao, especialidade) VALUES
            ('ceo',                      'Direção Executiva',   'Diretor Corporativo', 'exec', 'Estratégia e decisões', 'Governança, riscos, direção'),
            ('orchestrator',             'Orquestrador',        'Orquestrador',        'exec', 'Coordena agentes',      'Roteamento, priorização, QA'),
            ('analysts',                 'Analistas',           'Analistas',           'pes',  'Análises',              'Pesquisa e síntese'),
            ('commercial',               'Comercial',           'Comercial',           'com',  'Vendas e prospecção',   'CRM, propostas, contratos'),
            ('project-developers',       'Gestão de Projetos',  'Gerente de Projetos', 'eng',  'PMO e entregas',        'Planejamento, execução'),
            ('environmental',            'Ambiental',           'Especialista Ambiental','amb','Licenciamento, PRAD',  'EIA/RIMA, geotecnologias');
    END IF;
END $$;

COMMIT;
