-- ============================================================================
-- Kraefegg M.O. — banco de dados (PostgreSQL 14+)
-- Schema de produção: núcleo, CRM, demandas/projetos, monitoramento/telemetria
-- e financeiro. Modelo 100% funcional e dinâmico (triggers + views executivas).
-- Autor: time de dados (data-analytics / data-engineering) · pt-BR
-- ============================================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS kraefegg;
SET search_path TO kraefegg, public;

-- ============================================================================
-- TIPOS (enums)
-- ============================================================================

CREATE TYPE prioridade        AS ENUM ('baixa', 'media', 'alta', 'critica');
CREATE TYPE status_funil      AS ENUM ('prospecto', 'contatado', 'reuniao_marcada', 'proposta', 'negociacao', 'fechado', 'perdido', 'desqualificado');
CREATE TYPE status_proposta   AS ENUM ('rascunho', 'enviada', 'em_negociacao', 'aprovada', 'rejeitada', 'cancelada');
CREATE TYPE status_contrato   AS ENUM ('ativo', 'suspenso', 'encerrado');
CREATE TYPE status_projeto    AS ENUM ('backlog', 'analise', 'execucao', 'revisao', 'concluido', 'cancelado');
CREATE TYPE fase_demanda      AS ENUM ('backlog', 'analise', 'execucao', 'revisao', 'concluida');
CREATE TYPE recorrencia       AS ENUM ('unico', 'mensal', 'trimestral', 'anual');
CREATE TYPE canal_contato     AS ENUM ('email', 'whatsapp', 'telefone', 'linkedin', 'presencial', 'outro');
CREATE TYPE tipo_site         AS ENUM ('estacao_meteorologica', 'umidade_solo', 'datalogger_rio', 'qualidade_ar', 'parcela_ndvi');
CREATE TYPE origem_serie      AS ENUM ('real', 'modelo');
CREATE TYPE indice_espectral  AS ENUM ('ndvi', 'ndwi', 'umidade', 'bsi');
CREATE TYPE severidade        AS ENUM ('baixa', 'media', 'alta', 'critica');
CREATE TYPE qualidade_leitura AS ENUM ('ok', 'suspeita', 'invalida');
CREATE TYPE status_lancamento AS ENUM ('previsto', 'realizado', 'cancelado');
CREATE TYPE tipo_lancamento   AS ENUM ('receita', 'despesa');
CREATE TYPE forma_pagamento   AS ENUM ('pix', 'boleto', 'cartao', 'transferencia', 'dinheiro', 'outro');
CREATE TYPE status_cobranca   AS ENUM ('aberta', 'paga', 'atrasada', 'cancelada');
CREATE TYPE status_interacao  AS ENUM ('aberto', 'agendada', 'concluida', 'perdida');

-- ============================================================================
-- NÚCLEO ORGANIZACIONAL
-- ============================================================================

CREATE TABLE areas_departamento (
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo     text UNIQUE NOT NULL,          -- exec, orc, eng, amb, min, ene, com, pes, seg
    nome       text NOT NULL,
    cor        text NOT NULL,                 -- hex usada no HQ
    descricao  text
);

CREATE TABLE agentes (
    id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo       text UNIQUE NOT NULL,        -- id do agente no HQ (ceo, iot-embedded...)
    nome         text NOT NULL,
    cargo        text NOT NULL,
    area_id      int REFERENCES areas_departamento(id),
    funcao       text,
    especialidade text,
    modelo_ia    text NOT NULL DEFAULT 'omniroute/auto/best-reasoning',
    permissao    jsonb NOT NULL DEFAULT '{}'::jsonb,
    ativo        boolean NOT NULL DEFAULT true,
    criado_em    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE fases (
    id      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo  text UNIQUE NOT NULL,             -- backlog, analise, execucao, revisao, concluida
    nome    text NOT NULL,
    ordem   int NOT NULL,
    cor     text NOT NULL
);

-- ============================================================================
-- CRM / COMERCIAL
-- ============================================================================

CREATE TABLE segmentos_mercado (
    id     int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo text UNIQUE NOT NULL,              -- mineracao, energia, ambiental, agro, sst, governo, offshore
    nome   text NOT NULL
);

CREATE TABLE clientes (
    id               int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razao_social     text NOT NULL,
    nome_fantasia    text,
    documento        text UNIQUE,
    segmento_id      int REFERENCES segmentos_mercado(id),
    cidade           text,
    uf               char(2),
    status           status_funil NOT NULL DEFAULT 'prospecto',
    fonte            text,
    site_url         text,
    valor_estimado   numeric(14,2),
    observacoes      text,
    criado_em        timestamptz NOT NULL DEFAULT now(),
    atualizado_em    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE contatos (
    id              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id      int NOT NULL REFERENCES clientes(id) ON DELETE CASCADE,
    nome            text NOT NULL,
    cargo           text,
    email           text,
    telefone        text,
    whatsapp        text,
    canal_preferido canal_contato NOT NULL DEFAULT 'email',
    ativo           boolean NOT NULL DEFAULT true,
    criado_em       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE interacoes (
    id             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contato_id     int NOT NULL REFERENCES contatos(id) ON DELETE CASCADE,
    canal          canal_contato NOT NULL,
    sentido        text NOT NULL CHECK (sentido IN ('outbound', 'inbound')),
    descricao      text,
    proximo_passo  text,
    data_agendada  timestamptz,
    status         status_interacao NOT NULL DEFAULT 'aberto',
    concluida_em   timestamptz,
    criado_em      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE propostas (
    id             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero         text UNIQUE NOT NULL,      -- P-2026-001
    cliente_id     int NOT NULL REFERENCES clientes(id),
    titulo         text NOT NULL,
    escopo         jsonb NOT NULL DEFAULT '{}'::jsonb,
    valor_total    numeric(14,2) NOT NULL DEFAULT 0,
    status         status_proposta NOT NULL DEFAULT 'rascunho',
    data_envio     date,
    validade_dias  int NOT NULL DEFAULT 15,
    responsavel_id int REFERENCES agentes(id),
    observacoes    text,
    criado_em      timestamptz NOT NULL DEFAULT now(),
    atualizado_em  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE itens_proposta (
    id             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposta_id    int NOT NULL REFERENCES propostas(id) ON DELETE CASCADE,
    descricao      text NOT NULL,
    tipo           text NOT NULL CHECK (tipo IN ('servico', 'assinatura', 'kit')),
    quantidade     numeric(10,2) NOT NULL DEFAULT 1,
    valor_unitario numeric(14,2) NOT NULL DEFAULT 0,
    recorrencia    recorrencia NOT NULL DEFAULT 'unico',
    desconto_pct   numeric(5,2) NOT NULL DEFAULT 0
);

CREATE TABLE contratos (
    id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero       text UNIQUE NOT NULL,        -- C-2026-001
    proposta_id  int UNIQUE REFERENCES propostas(id),
    cliente_id   int NOT NULL REFERENCES clientes(id),
    data_inicio  date NOT NULL,
    data_fim     date,
    valor_total  numeric(14,2) NOT NULL DEFAULT 0,
    recorrencia  recorrencia NOT NULL DEFAULT 'unico',
    sla          jsonb NOT NULL DEFAULT '{}'::jsonb,
    clausulas    jsonb NOT NULL DEFAULT '{}'::jsonb,
    status       status_contrato NOT NULL DEFAULT 'ativo',
    criado_em    timestamptz NOT NULL DEFAULT now(),
    atualizado_em timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE cobrancas (
    id             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contrato_id    int NOT NULL REFERENCES contratos(id) ON DELETE CASCADE,
    parcela        int NOT NULL DEFAULT 1,
    competencia    date NOT NULL,             -- mês de referência (1º dia)
    descricao      text,
    valor          numeric(14,2) NOT NULL,
    vencimento     date NOT NULL,
    status         status_cobranca NOT NULL DEFAULT 'aberta',
    data_pagamento date,
    metodo         forma_pagamento,
    UNIQUE (contrato_id, parcela)
);

-- ============================================================================
-- DEMANDAS & PROJETOS
-- ============================================================================

CREATE TABLE projetos (
    id             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo         text UNIQUE NOT NULL,      -- PRJ-2026-001
    nome           text NOT NULL,
    descricao      text,
    cliente_id     int REFERENCES clientes(id),
    contrato_id    int REFERENCES contratos(id),
    responsavel_id int REFERENCES agentes(id),
    status         status_projeto NOT NULL DEFAULT 'backlog',
    prioridade     prioridade NOT NULL DEFAULT 'media',
    progresso      numeric(5,1) NOT NULL DEFAULT 0 CHECK (progresso BETWEEN 0 AND 100),
    data_inicio    date,
    data_fim       date,
    criado_em      timestamptz NOT NULL DEFAULT now(),
    atualizado_em  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE demandas (
    id             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projeto_id     int REFERENCES projetos(id) ON DELETE SET NULL,
    codigo         text UNIQUE NOT NULL,      -- D-01
    titulo         text NOT NULL,
    descricao      text,
    area_id        int REFERENCES areas_departamento(id),
    responsavel_id int REFERENCES agentes(id),
    fase           fase_demanda NOT NULL DEFAULT 'backlog',
    prioridade     prioridade NOT NULL DEFAULT 'media',
    progresso      int NOT NULL DEFAULT 0 CHECK (progresso BETWEEN 0 AND 100),
    prazo          date,
    criado_em      timestamptz NOT NULL DEFAULT now(),
    atualizado_em  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE historico_demandas (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demanda_id        int NOT NULL REFERENCES demandas(id) ON DELETE CASCADE,
    fase_anterior     fase_demanda,
    fase_nova         fase_demanda,
    progresso_anterior int,
    progresso_novo    int,
    agente_autor_id   int REFERENCES agentes(id),
    alterado_em       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE etapas_projeto (
    id            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projeto_id    int NOT NULL REFERENCES projetos(id) ON DELETE CASCADE,
    nome          text NOT NULL,
    ordem         int NOT NULL,
    peso          numeric(5,2) NOT NULL DEFAULT 1 CHECK (peso > 0),
    status        status_projeto NOT NULL DEFAULT 'backlog',
    data_prevista date,
    data_real     date
);

-- ============================================================================
-- MONITORAMENTO & TELEMETRIA
-- ============================================================================

CREATE TABLE sites (
    id              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          text UNIQUE NOT NULL,     -- STA-M1, PAR-01, RIO-01...
    nome            text NOT NULL,
    tipo            tipo_site NOT NULL,
    cliente_id      int REFERENCES clientes(id),
    contrato_id     int REFERENCES contratos(id),
    latitude        numeric(9,6),
    longitude       numeric(9,6),
    municipio       text,
    uf              char(2),
    status          text NOT NULL DEFAULT 'ativo' CHECK (status IN ('ativo', 'inativo', 'manutencao')),
    data_instalacao date,
    metadados       jsonb NOT NULL DEFAULT '{}'::jsonb,
    criado_em       timestamptz NOT NULL DEFAULT now(),
    atualizado_em   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE sensores (
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    int NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
    codigo     text NOT NULL,                 -- TEMP-01, SOLO-01...
    nome       text NOT NULL,
    grandeza   text NOT NULL,                 -- temperatura, umidade_rel, pressao, velocidade_vento, precipitacao, radiacao, umidade_solo, nivel_rio, aqi
    unidade    text,
    modelo     text,
    fabricante text,
    ativo      boolean NOT NULL DEFAULT true,
    UNIQUE (site_id, codigo)
);

CREATE TABLE leituras (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id  int NOT NULL REFERENCES sensores(id) ON DELETE CASCADE,
    instante   timestamptz NOT NULL,
    valor      numeric(14,4) NOT NULL,
    qualidade  qualidade_leitura NOT NULL DEFAULT 'ok'
);
CREATE INDEX idx_leituras_sensor_instante ON leituras (sensor_id, instante DESC);
CREATE INDEX idx_leituras_instante       ON leituras (instante);
COMMENT ON TABLE leituras IS 'Série temporal. Em produção: particionar por range(instante) ou usar TimescaleDB (hypertable).';

CREATE TABLE series_indices (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id   int NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
    indice    indice_espectral NOT NULL,
    data      date NOT NULL,
    valor     numeric(8,4) NOT NULL,
    origem    origem_serie NOT NULL,
    fonte     text,
    metadados jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (site_id, indice, data, origem)
);

CREATE TABLE eventos_inpe (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora  timestamptz NOT NULL,
    latitude   numeric(9,6) NOT NULL,
    longitude  numeric(9,6) NOT NULL,
    frp        numeric(8,2),
    bioma      text,
    municipio  text,
    uf         char(2),
    recebido_em timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_inpe_data ON eventos_inpe (data_hora);

CREATE TABLE dados_climaticos (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id          int NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
    instante_previsao timestamptz NOT NULL,
    horario          timestamptz NOT NULL,
    temperatura      numeric(6,2),
    umidade          numeric(5,2),
    velocidade_vento numeric(6,2),
    direcao_vento    int,
    precipitacao     numeric(6,2),
    radiacao         numeric(8,2),
    UNIQUE (site_id, horario)
);

CREATE TABLE alertas (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id         int REFERENCES sites(id) ON DELETE CASCADE,
    tipo            text NOT NULL,            -- queimada, cheia, seca, qualidade_ar, inversao
    severidade      severidade NOT NULL DEFAULT 'media',
    mensagem        text,
    acao_recomendada text,
    geojson         jsonb,
    lida            boolean NOT NULL DEFAULT false,
    respondida      boolean NOT NULL DEFAULT false,
    criado_em       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_alertas_nao_lidas ON alertas (lida) WHERE lida = false;

-- ============================================================================
-- FINANCEIRO
-- ============================================================================

CREATE TABLE categorias_lancamento (
    id     int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo text UNIQUE NOT NULL,
    nome   text NOT NULL,
    tipo   tipo_lancamento NOT NULL
);

CREATE TABLE lancamentos (
    id              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data            date NOT NULL,
    tipo            tipo_lancamento NOT NULL,
    categoria_id    int REFERENCES categorias_lancamento(id),
    descricao       text NOT NULL,
    valor           numeric(14,2) NOT NULL CHECK (valor >= 0),
    forma_pagamento forma_pagamento,
    contrato_id     int REFERENCES contratos(id) ON DELETE SET NULL,
    projeto_id      int REFERENCES projetos(id) ON DELETE SET NULL,
    status          status_lancamento NOT NULL DEFAULT 'previsto',
    criado_em       timestamptz NOT NULL DEFAULT now(),
    atualizado_em   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE kits (
    id                  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo              text UNIQUE NOT NULL, -- KIT-EST, KIT-SOLO, KIT-RIO, KIT-AQI
    nome                text NOT NULL,
    descricao           text,
    custo_bom           numeric(12,2) NOT NULL DEFAULT 0,
    preco_venda         numeric(12,2) NOT NULL DEFAULT 0,
    recorrencia_servico recorrencia NOT NULL DEFAULT 'mensal',
    ativo               boolean NOT NULL DEFAULT true
);

CREATE TABLE vendas_kits (
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero     text UNIQUE NOT NULL,          -- VENDA-2026-001
    cliente_id int NOT NULL REFERENCES clientes(id),
    data       date NOT NULL DEFAULT CURRENT_DATE,
    status     text NOT NULL DEFAULT 'orcamento'
               CHECK (status IN ('orcamento', 'aprovada', 'pago', 'enviado', 'entregue', 'cancelada')),
    criado_em  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE itens_venda (
    id             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venda_id       int NOT NULL REFERENCES vendas_kits(id) ON DELETE CASCADE,
    kit_id         int NOT NULL REFERENCES kits(id),
    quantidade     int NOT NULL DEFAULT 1,
    preco_unitario numeric(12,2) NOT NULL,
    UNIQUE (venda_id, kit_id)
);

CREATE TABLE custos_projeto (
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projeto_id  int NOT NULL REFERENCES projetos(id) ON DELETE CASCADE,
    categoria_id int REFERENCES categorias_lancamento(id),
    descricao   text NOT NULL,
    valor       numeric(12,2) NOT NULL,
    data        date NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE configuracoes (
    chave         text PRIMARY KEY,
    valor         jsonb NOT NULL,
    descricao     text,
    atualizado_em timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE auditoria (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabela          text NOT NULL,
    registro_id     int NOT NULL,
    acao            text NOT NULL CHECK (acao IN ('INSERT', 'UPDATE', 'DELETE')),
    dados_antes     jsonb,
    dados_depois    jsonb,
    agente_autor_id int REFERENCES agentes(id),
    em              timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_auditoria_tabela ON auditoria (tabela, registro_id);

-- ============================================================================
-- FUNÇÕES & TRIGGERS
-- ============================================================================

-- 1) mantém atualizado_em
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.atualizado_em := now();
    RETURN NEW;
END; $$ LANGUAGE plpgsql;

DO $$
DECLARE t text;
BEGIN
    FOREACH t IN ARRAY ARRAY['clientes', 'propostas', 'contratos', 'projetos',
                             'demandas', 'sites', 'lancamentos', 'vendas_kits', 'configuracoes']
    LOOP
        EXECUTE format('CREATE TRIGGER trg_%s_updated BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at()', t, t);
    END LOOP;
END $$;

-- 2) demandas: concluída ⇒ progresso 100; loga histórico; recalcula progresso do projeto
CREATE OR REPLACE FUNCTION fn_demanda_trigger() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'UPDATE' AND (NEW.fase IS DISTINCT FROM OLD.fase
                          OR NEW.progresso IS DISTINCT FROM OLD.progresso) THEN
        IF NEW.fase = 'concluida' THEN NEW.progresso := 100; END IF;
        INSERT INTO historico_demandas (demanda_id, fase_anterior, fase_nova,
                                        progresso_anterior, progresso_novo, agente_autor_id)
        VALUES (NEW.id, OLD.fase, NEW.fase, OLD.progresso, NEW.progresso, NEW.responsavel_id);
        IF NEW.projeto_id IS NOT NULL THEN
            UPDATE projetos SET progresso = COALESCE((SELECT ROUND(AVG(progresso))
                                                      FROM demandas WHERE projeto_id = NEW.projeto_id), 0)
            WHERE id = NEW.projeto_id AND status NOT IN ('concluido', 'cancelado');
        END IF;
    ELSIF TG_OP = 'INSERT' THEN
        IF NEW.fase = 'concluida' THEN NEW.progresso := 100; END IF;
        IF NEW.projeto_id IS NOT NULL THEN
            UPDATE projetos SET progresso = COALESCE((SELECT ROUND(AVG(progresso))
                                                      FROM demandas WHERE projeto_id = NEW.projeto_id), 0)
            WHERE id = NEW.projeto_id AND status NOT IN ('concluido', 'cancelado');
        END IF;
    END IF;
    RETURN NEW;
END; $$ LANGUAGE plpgsql;

CREATE TRIGGER trg_demanda
    BEFORE INSERT OR UPDATE ON demandas
    FOR EACH ROW EXECUTE FUNCTION fn_demanda_trigger();

-- 3) auditoria genérica (clientes, propostas, contratos)
CREATE OR REPLACE FUNCTION fn_auditar() RETURNS trigger AS $$
DECLARE
    antes  jsonb;
    depois jsonb;
BEGIN
    antes  := CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN to_jsonb(OLD) ELSE NULL END;
    depois := CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN to_jsonb(NEW) ELSE NULL END;
    INSERT INTO auditoria (tabela, registro_id, acao, dados_antes, dados_depois)
    VALUES (TG_TABLE_NAME, COALESCE(NEW.id, OLD.id), TG_OP, antes, depois);
    RETURN COALESCE(NEW, OLD);
END; $$ LANGUAGE plpgsql;

CREATE TRIGGER trg_clientes_audit  AFTER INSERT OR UPDATE OR DELETE ON clientes  FOR EACH ROW EXECUTE FUNCTION fn_auditar();
CREATE TRIGGER trg_propostas_audit AFTER INSERT OR UPDATE OR DELETE ON propostas FOR EACH ROW EXECUTE FUNCTION fn_auditar();
CREATE TRIGGER trg_contratos_audit AFTER INSERT OR UPDATE OR DELETE ON contratos FOR EACH ROW EXECUTE FUNCTION fn_auditar();

-- ============================================================================
-- VIEWS EXECUTIVAS (painel dinâmico)
-- ============================================================================

CREATE VIEW v_funil_comercial AS
SELECT
    count(*) FILTER (WHERE status = 'prospecto')        AS prospectos,
    count(*) FILTER (WHERE status = 'contatado')        AS contatados,
    count(*) FILTER (WHERE status = 'reuniao_marcada')  AS reunioes,
    count(*) FILTER (WHERE status = 'proposta')         AS propostas,
    count(*) FILTER (WHERE status = 'negociacao')       AS negociacoes,
    count(*) FILTER (WHERE status = 'fechado')          AS fechados,
    count(*) FILTER (WHERE status = 'perdido')          AS perdidos,
    COALESCE(sum(valor_estimado) FILTER (WHERE status IN ('proposta', 'negociacao')), 0) AS pipeline_valor
FROM clientes;

CREATE VIEW v_propostas_detalhe AS
SELECT p.id, p.numero, p.titulo, p.valor_total, p.status, p.data_envio, p.validade_dias,
       c.nome_fantasia, c.razao_social, c.uf, a.nome AS responsavel
FROM propostas p
JOIN clientes c ON c.id = p.cliente_id
LEFT JOIN agentes a ON a.id = p.responsavel_id;

CREATE VIEW v_demandas_abertas AS
SELECT d.id, d.codigo, d.titulo, d.prioridade, d.prazo, d.progresso,
       f.nome AS fase, f.cor AS cor_fase,
       a.nome AS responsavel, ad.nome AS area, pr.codigo AS projeto
FROM demandas d
JOIN fases f ON f.codigo = d.fase::text
LEFT JOIN agentes a             ON a.id = d.responsavel_id
LEFT JOIN areas_departamento ad ON ad.id = d.area_id
LEFT JOIN projetos pr           ON pr.id = d.projeto_id
WHERE d.fase <> 'concluida'
ORDER BY d.prazo NULLS LAST, d.prioridade DESC, d.id;

CREATE VIEW v_telemetria_ultima AS
SELECT DISTINCT ON (se.id)
       s.codigo AS site, s.nome AS site_nome, se.codigo AS sensor, se.grandeza, se.unidade,
       l.instante, l.valor, l.qualidade
FROM sensores se
JOIN sites s ON s.id = se.site_id
LEFT JOIN leituras l ON l.sensor_id = se.id
ORDER BY se.id, l.instante DESC;

CREATE VIEW v_ndvi_serie AS
SELECT s.codigo AS site, si.indice, si.data, si.valor, si.origem, si.fonte
FROM series_indices si
JOIN sites s ON s.id = si.site_id
ORDER BY s.codigo, si.indice, si.data;

CREATE VIEW v_fluxo_caixa_mensal AS
SELECT date_trunc('month', data)::date AS mes,
       tipo,
       sum(valor) FILTER (WHERE status = 'realizado') AS realizado,
       sum(valor) FILTER (WHERE status = 'previsto')  AS previsto
FROM lancamentos
WHERE status <> 'cancelado'
GROUP BY 1, 2
ORDER BY 1;

CREATE VIEW v_resumo_financeiro AS
SELECT
    (SELECT COALESCE(sum(valor),0) FROM lancamentos WHERE tipo = 'receita' AND status = 'realizado') AS receita_realizada,
    (SELECT COALESCE(sum(valor),0) FROM lancamentos WHERE tipo = 'despesa' AND status = 'realizado') AS despesa_realizada,
    (SELECT COALESCE(sum(valor),0) FROM lancamentos WHERE tipo = 'receita' AND status = 'previsto')  AS receita_prevista,
    (SELECT COALESCE(sum(valor),0) FROM lancamentos WHERE tipo = 'despesa' AND status = 'previsto')  AS despesa_prevista,
    (SELECT COALESCE(sum(valor),0) FROM cobrancas WHERE status IN ('aberta', 'atrasada'))           AS a_receber;

CREATE VIEW v_margem_proposta AS
SELECT p.id, p.numero, p.titulo, p.valor_total,
       COALESCE(sum(i.valor_unitario * i.quantidade), 0) AS total_itens,
       p.valor_total - COALESCE(sum(i.valor_unitario * i.quantidade), 0) AS diferenca
FROM propostas p
LEFT JOIN itens_proposta i ON i.proposta_id = p.id
GROUP BY p.id, p.numero, p.titulo, p.valor_total;

CREATE VIEW v_painel_executivo AS
SELECT
    (SELECT count(*) FROM agentes WHERE ativo)                                                     AS agentes_ativos,
    (SELECT count(*) FROM demandas WHERE fase <> 'concluida')                                       AS demandas_abertas,
    (SELECT count(*) FROM clientes WHERE status IN ('proposta', 'negociacao'))                      AS oportunidades,
    (SELECT COALESCE(sum(valor_estimado),0) FROM clientes WHERE status IN ('proposta', 'negociacao')) AS pipeline_valor,
    (SELECT COALESCE(sum(valor),0) FROM cobrancas
        WHERE status = 'paga' AND date_trunc('month', data_pagamento) = date_trunc('month', CURRENT_DATE)) AS receita_mes,
    (SELECT count(*) FROM alertas WHERE lida = false)                                                AS alertas_nao_lidas;

COMMIT;
